/* Dataset freshness, computed against the READER's clock.
 *
 * Static conversion, Pass C. Everything else in the payload is a pure function
 * of the xlsx and can be frozen at build time (see
 * docs/diagnostics/static-feasibility.md). This is the one thing that cannot:
 * "how old is this data" is a question about *now*, and a value baked into the
 * build would answer it as of the build and then quietly go on being wrong —
 * the exact silent-staleness failure the indicator exists to prevent.
 *
 * So the comparison lives here, on the client. What does NOT live here is the
 * calendar: the age is counted in KR business days, and re-implementing the
 * holiday table in TypeScript would create a second calendar that must never
 * disagree with the curve's. Instead the manifest ships the next 400 business
 * days after `asof`, generated by the frozen engine's own
 * `_is_kr_business_day`, and this counts how many have passed.
 */

export interface Manifest {
  asof: string;
  dataHash: string;
  schemaVersion: number;
  rows: number;
  missingNodes: string[];
  seriesCount: number;
  /** ISO dates, ascending, strictly after `asof`. */
  businessDaysAfter: string[];
  freshnessThresholds: { behind: number; stale: number };
  builtAt: string;
}

export type FreshnessLevel = "current" | "behind" | "stale";

export interface Freshness {
  asOf: string;
  today: string;
  ageBusinessDays: number;
  level: FreshnessLevel;
}

/** The market's timezone. The data is KRW IRS closes and the ladder counts KR
 * business days, so "which day is it" is a question about Seoul, not about the
 * reader. */
export const MARKET_TZ = "Asia/Seoul";

/* Built once: constructing an Intl.DateTimeFormat per call is the expensive
 * part, and this runs on every render of the header. `en-CA` yields
 * YYYY-MM-DD, which is what the ladder is compared against. */
const seoulParts = new Intl.DateTimeFormat("en-CA", {
  timeZone: MARKET_TZ,
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
});

/** The calendar date in Seoul at the reader's instant (Pass I).
 *
 * The reader's *instant* is the right input; the reader's *local date* is not.
 * A reader in London at 22:00 on the 29th is already on the 30th in Seoul, and
 * one in New York at 21:00 is on the 30th too — both would previously have
 * counted a business day late, every evening. Conversely `toISOString()` would
 * report yesterday all morning for a reader actually in Seoul.
 *
 * Via `Intl`, not a fixed +9: KST has no DST today, but "Korea is UTC+9" is a
 * fact about the world, and facts about the world belong in the platform's
 * timezone database rather than in this file, where nobody would think to
 * revisit it. */
export function marketIsoDate(d: Date = new Date()): string {
  return seoulParts.format(d);
}

export function freshnessFrom(m: Manifest, now: Date = new Date()): Freshness {
  const today = marketIsoDate(now);
  const days = m.businessDaysAfter ?? [];
  /* STRICTLY BEFORE today — the 전일종가 rule [OWNER, 2026-08-05]. The loader
   * drops today's intraday row, so the freshest possible asof is the last
   * business day before today; today itself is never a close the file could
   * hold, and counting it (the old `<=`) would read every dataset as
   * permanently one day behind. Age = completed closes the tree is missing.
   * String compare is safe and total on zero-padded ISO dates. */
  let age = 0;
  while (age < days.length && days[age] < today) age++;
  const { behind, stale } = m.freshnessThresholds;
  return {
    asOf: m.asof,
    today,
    ageBusinessDays: age,
    level: age >= stale ? "stale" : age >= behind ? "behind" : "current",
  };
}
