/* Dataset freshness, computed against the READER's clock.
 *
 * Static conversion, Pass C. Everything else in the payload is a pure function
 * of the xlsx and can be frozen at build time (see
 * docs/diagnostics/static-feasibility.md). This is the one thing that cannot:
 * "how old is this data" is a question about *now*, and a value baked into the
 * build would answer it as of the build and then quietly go on being wrong —
 * the exact silent-staleness failure the indicator exists to prevent.
 *
 * So the comparison lives here, on the client. What does NOT live here is the
 * calendar: the age is counted in KR business days, and re-implementing the
 * holiday table in TypeScript would create a second calendar that must never
 * disagree with the curve's. Instead the manifest ships the next 400 business
 * days after `asof`, generated by the frozen engine's own
 * `_is_kr_business_day`, and this counts how many have passed.
 */

export interface Manifest {
  asof: string;
  dataHash: string;
  schemaVersion: number;
  rows: number;
  missingNodes: string[];
  seriesCount: number;
  /** ISO dates, ascending, strictly after `asof`. */
  businessDaysAfter: string[];
  freshnessThresholds: { behind: number; stale: number };
  builtAt: string;
}

export type FreshnessLevel = "current" | "behind" | "stale";

export interface Freshness {
  asOf: string;
  today: string;
  ageBusinessDays: number;
  level: FreshnessLevel;
}

/** Local calendar date as ISO — NOT `toISOString()`, which converts to UTC and
 * would report yesterday for anyone east of Greenwich after 09:00 local. Seoul
 * is UTC+9, so that mistake would be visible here every single morning. */
export function localIsoDate(d: Date): string {
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

export function freshnessFrom(m: Manifest, now: Date = new Date()): Freshness {
  const today = localIsoDate(now);
  const days = m.businessDaysAfter ?? [];
  // string compare is safe and total on zero-padded ISO dates
  let age = 0;
  while (age < days.length && days[age] <= today) age++;
  const { behind, stale } = m.freshnessThresholds;
  return {
    asOf: m.asof,
    today,
    ageBusinessDays: age,
    level: age >= stale ? "stale" : age >= behind ? "behind" : "current",
  };
}
